language: swift
osx_image: xcode8.3
script:
    - xcodebuild -showsdks
    - instruments -s devices
    - xcodebuild test -workspace Meow.xcworkspace -scheme Meow -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0'

